### PR TITLE
Add new plugin unique, to check last messages

### PR DESCRIPTION
**Pull request by 8of**
Fixes https://github.com/aahnik/tgcf/issues/578

I have fully read and understood the terms and conditions laid down in the general [Contributor License Agreement](https://aahnik.github.io/aahnik/CLA.html)

- [x] I agree to distribute my code contributions under MIT License, and will not change it in the future.
- [x] I agree that any contribution once merged, cannot be taken back by me.
- [x] I will abide by the Code of Conduct
- [x] I understand that the decision of the maintainer is final and abiding. And the maintainer reserves all rights to modify my code. I also understand that the maintainer can remove my code in future, if he thinks so.
- [x] Once my contribution is merged, my name will permanently appear in the Contribtor's List of this repository.

### CODE REVIEW

**Comment by aahnik** [comment]
Thank you so much @8of for this PR! Sorry for the slow response... I would review and integrate it with my codebase as soon as possible.

**Comment by ExMalthus** [comment]
> Thank you so much @8of for this PR! Sorry for the slow response... I would review and integrate it with my codebase as soon as possible.

Hi @aahnik, any progress with integrating this plugin? Looking forward to this sorely needed feature. Cheers!

**Comment by aahnik** [comment]
Sorry for the delays, I understand that this is a much needed feature, but i am unable to work on tgcf currently due to my current commitments.

I have a 3 mo summer break from May 6th, and I am looking forward to working on tgcf and popular feature requests.

You can expect this PR to get merged by 10th May.

Thank you so much for your contribution, and I again apologize for not being able to do justice this project.

**Review by aahnik — APPROVED** [review]
thank you so much for this contribution

**Pull request merged**
